const BOOKS = [
  {"no":1,"status":"published","title":"はじまった、副業なしで副収入 15万円から始める、小さなAI算力運用","image":"book4.jpg","amazon":"https://www.amazon.co.jp/dp/B0HJ62LS2L"},
  {"no":2,"status":"published","title":"初期15万円から、年利30%超を狙える！ 新しい市場が現れました","image":"book1.jpg","amazon":"https://www.amazon.co.jp/dp/B0HDHJT2P7"},
  {"no":3,"status":"published","title":"初期15万円から、年利30%超を狙える！ ローカルLLMとは？","image":"book2.jpg","amazon":"https://www.amazon.co.jp/dp/B0HFZ66FZG"},
  {"no":4,"status":"published","title":"起業1年目の経営者のための AI算力運用事業とは？","image":"book3.jpg","amazon":"https://www.amazon.co.jp/dp/B0HGPJK2TD"},
  {"no":5,"status":"published","title":"Kindle本の書き方・自叙伝編","image":"book5.jpg","amazon":"https://www.amazon.co.jp/dp/B0H3G8SMJM"},
  {"no":6,"status":"published","title":"終活ノートの書き方・思い出編","image":"book6.jpg","amazon":"https://www.amazon.co.jp/dp/B0GX2Y9998"},
  {"no":7,"status":"published","title":"台風の日は雑談日","image":"book7.jpg","amazon":"https://www.amazon.co.jp/dp/B0H46D81GJ"},
  {"no":8,"status":"published","title":"ChatGPTと作るnote入門","image":"book8.jpg","amazon":"https://www.amazon.co.jp/dp/B0H6TF6251"},
  {"no":9,"status":"published","title":"ChatGPTと作る Kindle出版入門","image":"book9.jpg","amazon":"https://www.amazon.co.jp/dp/B0H6Z9HTP4"},
  {"no":10,"status":"published","title":"ChatGPTと作る Kindle出版入門・実践編","image":"book10.jpg","amazon":"https://www.amazon.co.jp/dp/B0H7424X4V"},
  {"no":11,"status":"published","title":"ChatGPTと作る Kindle出版入門 雑談家ひとね編","image":"book11.jpg","amazon":"https://www.amazon.co.jp/dp/B0H7JLW6KT"},
  {"no":12,"status":"published","title":"世界一のチームづくり","image":"book12.jpg","amazon":"https://www.amazon.co.jp/dp/B0H6KYTSDZ"},
  {"no":13,"status":"published","title":"65歳、定年後の仕事。05 雑談家ひとねの百話集 下巻","image":"book13.jpg","amazon":"https://www.amazon.co.jp/dp/B0GZW9S374"},
  {"no":14,"status":"published","title":"65歳、定年後の仕事。04 雑談家ひとねの百話集 上巻","image":"book14.jpg","amazon":"https://www.amazon.co.jp/dp/B0H2C4T191"},
  {"no":15,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":16,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":17,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":18,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":19,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":20,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":21,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":22,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":23,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":24,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":25,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":26,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":27,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":28,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":29,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""},
  {"no":30,"status":"comingsoon","title":"Coming Soon","image":"","amazon":""}
];
